server:
 port: 8080
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: db_user
    password: db_password

  security:
    user:
      name: name
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true


logging:   #logging
  file:
    name: log/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.tpe]': INFO

management:   # actuator
  endpoints:
    web:
      exposure:
        include: ['health','loggers','env','beans']
